### ISSUE TITLE
implement login and authentication

### ISSUE THREAD

**Issue by torbengb** [torbengb/toolpool#2]
- put a "current user" dropdown on the index page for now.
- figure out how to remember the user across pages.
- use this for "loaned to" and for new-tool "owner".

**Comment by KlaymenDK** [comment]
Don't.

Use a framework already, instead of re-inventing the wheel.

**Comment by torbengb** [comment]
Yes, obviously a necessary step. (But I need to learn to walk before I can run.)

**[Laravel](https://laravel.com/)** seems to be the most sensible choice, not necessarily the easiest but by far most used.

Example commentary: https://athemes.com/collections/best-php-frameworks/

**Comment by torbengb** [comment]
Framework wil be implemented with issue #12.

**Comment by torbengb** [comment]
Rudimentary functionality for "current user" and "logout" is implemented!
